name: Alert Workflow

on:
  push:
    branches:
      - main

jobs:
  send-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Simular alerta
        run: |
          echo "Simulando alerta..."
          exit 1  # Este comando força uma falha, gerando alerta
