name: Python CI

on:
  pull_request:
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
      # Realiza o checkout do repositório no ambiente de execução.

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      # Define a versão do Python a ser usada no ambiente.

    - name: Exibir versão do Python
      run: python --version
      # Exibe a versão do Python instalada.

    - name: Instalar dependências
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Instala as dependências do projeto, caso o arquivo requirements.txt exista.

    - name: Rodar script
      run: python atv01.py
      # Executa o script Python principal do repositório.

    - name: Exibir conteúdo do repositório
      run: ls -la
      # Exibe o conteúdo do repositório para verificação.
